#! /bin/env bash

if [ "$#" -lt 2 ]; then
    echo "Usage: <production|staging> <commit message> [--no-dist]"
    exit 1
fi

echo ">>>> Env: $1"
echo ">>>> Message: $2"


if echo $* | grep -e "--no-dist" -q
then
    echo ">>>> Skipping Dist step"
else
    gulp dist
    git checkout master
    git add .
    git commit -m "$1: $2"
fi

echo ">>>> Merging master with $1"
git checkout "$1"
git merge master

if [ "$1" == "production" ]
then
    echo ">>>> pushing [production] -> heroku[master]"
    git push heroku production:master
    APP=magnovite-2015
else
    echo ">>>> pushing [staging] -> staging[master]"
    git push staging staging:master
    APP=magnovite-staging
fi

if echo $* | grep -e "--no-migrate" -q
then
    echo ">>>> Skipping Migrating step"
else
    echo ">>>> Migrationg heroku app $APP"
    heroku run ./manage.py migrate --app="$APP"
fi

git checkout master
git merge production
git push origin master
