/* global require */

var gulp = require('gulp');
var usemin = require('gulp-usemin');
var uglify = require('gulp-uglify');
var minifyHtml = require('gulp-minify-html');
var minifyCss = require('gulp-minify-css');
var rev = require('gulp-rev');
var clean = require('gulp-clean');
var runSequence = require('run-sequence');

gulp.task('dist', function(cb) {
    'use strict';

    runSequence(['clean', 'usemin'], 'move-usemin', 'clean-usemin');
});

/**
 * Concats and builds the html
 */
gulp.task('usemin', function() {
    'use strict';

    return gulp.src('app/templates/*.html')
        .pipe(usemin({
            css: [minifyCss(), rev()],
            js: [uglify(), rev()]
        }))
        .pipe(gulp.dest('app/templates/tmp'));
});

/**
 * Moves the files generated by usemin to the
 * correct folder
 */
gulp.task('move-usemin', function() {
    'use strict';

    // move templates
    gulp.src('app/templates/tmp/*.html', {base: 'app/templates/tmp/'})
        .pipe(gulp.dest('app/templates/dist'));

    // move css files
    var files = [
        'app/templates/tmp/static/dist/*.css',
        'app/templates/tmp/static/dist/*.js'
    ];

    return gulp.src(files, {base: 'app/templates/tmp/static/'})
        .pipe(gulp.dest('app/static/'));

});

/**
 * Cleans the extra files created by usemin
 * after they are moved
 */
gulp.task('clean-usemin', function() {
    'use strict';

    return gulp.src('app/templates/tmp', {read: false})
    .pipe(clean());
});

/**
 * Cleans all files created by dist
 */
gulp.task('clean', function() {
    'use strict';

    var dirs = [
        'app/templates/tmp',
        'app/templates/dist',
        'app/static/dist'
    ];

    return gulp.src(dirs, {read: false})
        .pipe(clean());
});
